version: '3'
services:
  frontend:
    build:
      context: ./Landing
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://neuroflex.ru:5000/send-email  # указать URL для API бэкенда
    depends_on:
      - backend

  backend:
    build:
      context: ./LandingBackend
    ports:
      - "5000:5000"
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always
