version: '3'
services:
  frontend:
    build:
      context: ./Landing
    ports:
      - "3000:3000"  # Внешний порт для фронтенда
    environment:
      - REACT_APP_API_URL=http://neuroflex.ru/send-email  # URL для API бэкенда
    depends_on:
      - backend

  backend:
    build:
      context: ./LandingBackend
    ports:
      - "5000:5000"  # Внешний порт для бэкенда
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always

  nginx:
    image: nginx:alpine  # Используем легковесный образ Nginx
    volumes:
      - ./nano.conf:/etc/nginx/nginx.conf:ro  # Монтируем вашу конфигурацию
      - ./Landing/build:/var/www/html/mydomain  # Монтируем скомпилированные файлы фронтенда
    ports:
      - "80:80"  # Для HTTP
      - "443:443"  # Для HTTPS
    depends_on:
      - frontend
      - backend
    restart: always
